import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ApolloWrapper } from "@/lib/apollo/ApolloClient";
import { NextAuthProvider, authOptions } from "@/lib/next-auth";
import { getServerSession } from "next-auth";
import themeConfig from "@/configs/themeConfig";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <meta
        name="description"
        content={`${themeConfig.templateName} – Material Design React Admin Dashboard Template – is the most developer friendly & highly customizable Admin Dashboard Template based on MUI v5.`}
      />
      <meta
        name="keywords"
        content="Material Design, MUI, Admin Template, React Admin Template"
      />
      <meta name="viewport" content="initial-scale=1, width=device-width" />
      <body className={inter.className}>
        {children}
        {/* <ApolloWrapper>
          <NextAuthProvider session={session}>{children}</NextAuthProvider>
        </ApolloWrapper> */}
      </body>
    </html>
  );
}
